name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  TEST_RUNNER_URI: /test/run.cfm

jobs:
  
  cfmatrix:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      
    #setup the matrix of CF Engines
    strategy:
      matrix:
        cfengine: ["lucee@5.3", "adobe@2018"]
    steps:
      - uses: actions/checkout@v2

      - name: Clone cfmatrix
        run: git clone --depth 1 https://github.com/foundeo/cfmatrix.git cfmatrix

      - name: Install cfmatrix
        run: bash ./cfmatrix/install.sh
        
      - name: Run Tests
        run: bash ./cfmatrix/run.sh
      
